apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: eesprit/voting-app-worker
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: REDIS_HOST
              value: redis
            - name: DB_HOST
              value: db